### ISSUE TITLE
Deploy frontend using Firebase Hosting and GitHub Actions (with preview)

### ISSUE THREAD

**Issue by DinuWije** [uwblueprint/starter-code-v2#83]
## **Context:**

[Research frontend hosting options](https://www.notion.so/Research-frontend-hosting-options-1c16ae955f8844e8ac464cb33bf1d8af)

- After researching different hosting options, we will now deploy using one of them

**Why Firebase Hosting?**

- Unlimited build minutes (via GitHub Actions for public repos)
- We're already using Firebase services - no need to add additional third party dependencies

**Why not the others?**

- Heroku: not particularly advantageous for hosting client apps, cold start in free tier unless we ping it continuously
- Netlify: 300 build minutes/month → according to DCC this is a real limitation
- Vercel: could actually be a good alternative, worth exploring as a second deployment option after setting up Firebase

## **Acceptance Criteria:**

- Frontend is hosted at https://uw-blueprint-starter-code.firebaseapp.com
- On every frontend PR (or branch push), create a deploy preview
- On every merge to main with frontend changes, deploy to production
- Document set up instructions, communicate to Planet Read

## **Dev Notes:**

- Secrets may need to be moved into a .env file under /frontend → dynamically create this file via GitHub Actions on deploy
- Deploy preview on push or PR to /frontend folder only
- Preview URL expiration time is configurable, channel name is configurable (check what characters are allowed, we typically use "/"s in branch names)

## Rabbit Holes:

**Comment by sherryhli** [comment]
Need to feature flag `SameSite` settings on `refreshToken` cookie so that they can be set on the preview deploys.
