### ISSUE TITLE
Migrate from GraphQL Playground to GraphiQL

### ISSUE THREAD

**Issue by sherryhli** [uwblueprint/starter-code-v2#89]
## Context

GraphQL Playground is being retired in favour of GraphiQL: https://github.com/graphql/graphql-playground/issues/1143. Keep an eye out on the linked issue for a migration guide.

## Acceptance Criteria
* <BACKEND_URL>/graphql should render GraphiQL instead of GraphQL Playground

## Dev Notes

* https://www.apollographql.com/docs/apollo-server/testing/build-run-queries/#graphql-playground
* https://github.com/graphql/graphql-playground/issues/1143

**Comment by alexguo8** [comment]
It appears that GraphQL Playground and GraphiQL are no longer merging due to lack of development work

https://github.com/graphql/graphql-playground/issues/1366 

As a result, should we close this issue?
